language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python ex1.py
  - python ex2.py
  - python ex3.py
  - python ex4.py
  - python ex5.py
  - python ex6.py
  - python ex7.py
  - pyhton ex8.py
